"""
Takip edilecek fon ve kurumlar.
İsimler SEC'in kendi kayıtlarındaki yazımlara göre ayarlandı.
"""

FONLAR = [
    "Berkshire Hathaway",
    "Vanguard Group Inc",
    "State Street Corp",
    "Bridgewater Associates",
    "Citadel Advisors LLC",
    "Renaissance Technologies",
    "Two Sigma Investments",
    "Millennium Management LLC",
    "Point72 Asset Management",
    "Elliott Investment Management",
    "Pershing Square Capital Management",
    "Tiger Global Management LLC",
    "Coatue Management LLC",
    "Lone Pine Capital LLC",
    "Viking Global Investors LP",
    "Appaloosa LP",
    "Third Point LLC",
    "Greenlight Capital",
    "Icahn Carl",
    "Soros Fund Management LLC",
    "Duquesne Family Office LLC",
    "ARK Investment Management LLC",
    "FMR LLC",
    "T. Rowe Price",
    "Capital Research Global Investors",
    "Wellington Management",
    "Invesco Ltd",
    "Geode Capital Management LLC",
    "Northern Trust",
    "JPMorgan Chase & Co",
    "Goldman Sachs Group Inc",
    "Bank of America",
    "Wells Fargo",
    "UBS Group",
    "Deutsche Bank AG",
    "Barclays PLC",
    "HSBC Holdings PLC",
    "Morgan Stanley Institutional Investment",
    "BlackRock Finance",
]